{
  extends: [
    'react-app',
    'react-app/jest',
    'airbnb',
  ],
  parserOptions: {
    project: './tsconfig.json',
  },
  rules: {
    array-bracket-spacing: [ 'error', 'always' ],
    object-curly-newline: 'off',
    semi: [ 'error', 'never' ],
    react/destructuring-assignment: 'off',
    react/function-component-definition: [ 2, { namedComponents: 'arrow-function' } ],
    react/jsx-no-constructed-context-values: 'off',
    react/prop-types: 'off',
    react/jsx-filename-extension: 'off',
  }
}
